- include_tasks: apt.yml

- include_tasks: aleph.yml
  when: "env == 'staging' or 'mockturtle' in group_names"

- include_tasks: hmadison.yml
  when: "env == 'staging' or 'mockturtle' in group_names"

- include_tasks: pushcx.yml

- name: configure root bashrc
  become: yes
  template:
    src: root_bashrc.j2
    dest: "/root/.bashrc"
    mode: '0644'
  tags: configuration

- name: copy up logrotate config
  copy: >
    src="{{ item.file }}"
    dest="{{ item.dest }}"
    owner=root
    group=root
    mode="0644"
  with_items:
    - { dest: "/etc", file: "logrotate.conf" }
    - { dest: "/root", file: ".inputrc" }
    - { dest: "/root", file: ".editrc" }

- name: copy up logrotate.d
  copy: src="logrotate.d" dest="/etc/" owner=root group=root mode="0644"

- name: remove logrotate package's cron job
  file:
    path: /etc/cron.daily/logrotate
    state: absent
