- include_tasks: apt.yml

- name: copy environment-agnostic nginx config files
  register: nginx_agnostic_config
  copy:
    src: _env/nginx
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

- name: copy environment-specific nginx config files
  register: nginx_specific_config
  copy:
    src: "{{ env }}/nginx"
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

- name: nginx_agnostic_config.changed
  ansible.builtin.debug:
    var: nginx_agnostic_config.changed

- name: nginx_specific_config.changed
  ansible.builtin.debug:
    var: nginx_specific_config.changed

- name: Create dhparams
  command: openssl dhparam -out /etc/ssl/dhparams.pem 2048
  args:
    creates: /etc/ssl/dhparams.pem

- name: Use new config
  when: nginx_agnostic_config.changed or nginx_specific_config.changed
  systemd:
    name: nginx
    state: reloaded

- name: Enable nginx at startup
  systemd:
    name: nginx
    enabled: yes
