- include_tasks: apt.yml

# DKIM
# ----
# $ openssl genrsa -out dkim.key 1024
# $ openssl rsa -in dkim.key -out dkim.pub -pubout -outform PEM
# $ grep -v -e '^-' dkim.pub | tr -d '\n'

- name: cp /etc/default/opendkim
  copy: >
    src={{ item.name }}
    dest=/{{ item.name }}
    owner=opendkim
    group=opendkim
    mode={{ item.mode }}
  with_items:
    - { name: 'etc/default/opendkim', mode: '0644' }
    - { name: 'etc/opendkim.conf',    mode: '0644' }
    - { name: 'etc/systemd/system/opendkim.service',    mode: '0644' }

- name: create shared socket dir
  file:
    path: /var/spool/postfix/opendkim
    owner: opendkim
    group: opendkim
    state: directory
    mode: 0755

- name: cp /etc/aliases
  register: postfix_aliases
  template: >
    src=etc/aliases
    dest=/etc/aliases
    owner=root
    group=root
    mode=644

- name: load aliases
  when: postfix_aliases.changed
  shell: newaliases

- name: cp /etc/postfix
  register: postfix_config
  template: >
    src=etc/postfix/{{ item.name }}
    dest=/etc/postfix/{{ item.name }}
    owner=root
    group=root
    mode={{ item.mode }}
  with_items:
    - { name: 'main.cf',   mode: '0644' }
    - { name: 'master.cf', mode: '0644' }

- name: add postfix to group for opendkim socket
  user:
    name: postfix
    groups: opendkim
    append: yes

- name: postfix reload
  when: postfix_config.changed or postfix_aliases.changed
  shell: postfix reload
